In [2]:
import torch
from torch import nn

In [3]:
lst = [[1,2,3], [10, 12, 13]]
lst

[[1, 2, 3], [10, 12, 13]]

In [4]:
type(lst)

list

In [5]:
tensor1 = torch.tensor(lst)
tensor1

tensor([[ 1,  2,  3],
        [10, 12, 13]])

In [7]:
import numpy as np

np_array  = np.array([[1,1], [1, 3]])

np_array

array([[1, 1],
       [1, 3]])

In [8]:
type(np_array)

numpy.ndarray

In [9]:
np_tensor = torch.from_numpy(np_array)

np_tensor

tensor([[1, 1],
        [1, 3]])

## Simple Neural Network in PyTorch

In [10]:
# A simple neural network with 1 input and 1 output (no hidden layer)
net = nn.Linear(in_features= 1, out_features= 1)  # -> univariate linear regression model
net

Linear(in_features=1, out_features=1, bias=True)

In [16]:
input_tensor  = torch.tensor([[0.3]])
input_tensor

tensor([[0.3000]])

In [17]:
y = net(input_tensor)
y

tensor([[-0.6040]], grad_fn=<AddmmBackward0>)

### Stacking Layers



In [13]:
n_features = 8

n_target = 1

model = nn.Sequential(
            nn.Linear(n_features, 20),
            nn.Linear(20, 15),
            nn.Linear(15, 10),
            nn.Linear(10, 4),
            nn.Linear(4, n_target)
)

model

Sequential(
  (0): Linear(in_features=8, out_features=20, bias=True)
  (1): Linear(in_features=20, out_features=15, bias=True)
  (2): Linear(in_features=15, out_features=10, bias=True)
  (3): Linear(in_features=10, out_features=4, bias=True)
  (4): Linear(in_features=4, out_features=1, bias=True)
)

## Optimizers in PyTorch

#### Stochastic Gradient Descent (SGD)

In [18]:
learning_rate = 1e-2 # 0.01 # Typical values range between 1e-2 to 1e-4
optimizer_sgd = torch.optim.SGD(net.parameters(), lr = learning_rate)

#### Adaptive Gradient (Adagrad)

In [19]:
optimizer_ada = torch.optim.Adagrad(net.parameters(), lr = learning_rate)

#### Root Mean Square Propagation (RMSprop)

In [20]:
optimizer_rms = torch.optim.RMSprop(net.parameters(), lr = learning_rate)

#### Adaptive Moment Estimation (Adam)

In [21]:
optimizer_adam = torch.optim.Adam(net.parameters(), lr = learning_rate)

See PyTorch documentation for more algorithms: https://pytorch.org/docs/stable/optim.html

## Loss functions in PyTorch

In [22]:
criterion = nn.MSELoss() # mean squared error loss

See PyTorch documentation for more loss functions: https://datagy.io/pytorch-loss-functions/